CREATE TABLE IF NOT EXISTS User (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(254) UNIQUE NOT NULL,
    Passhash VARCHAR(60) NOT NULL, 
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS Movie (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    MovieURL VARCHAR(254) NOT NULL, 
    MovieTitle VARCHAR(254) NOT NULL,
    MovieOverview VARCHAR(254) NOT NULL
);