CREATE TABLE IF NOT EXISTS User (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(254) UNIQUE NOT NULL,
    Passhash VARCHAR(60) NOT NULL, 
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(128) NOT NULL
);